baseURL = "http://example.org/"
languageCode = "ja"
title = "ASRobot"
theme = "mainroad"
hasCJKLanguage = true
summaryLength = 200

[author]
name = "AtsushiSaito"
bio = "ものづくり大好きマン"
job = "SoftwareEngineer"
location = "Japan"

[Params]
subtitle = "ものづくり情報を発信します。"
schema = true
toc = true
post_meta = ["date", "categories"]
dateformat = "2006-01-02"
copyright = "AtsushiSaito"
readmore = true

[permalinks]
blog = "/:section/:year/:month/:day/:15:04"

[Params.sidebar]
home = "right" # Configure layout for home page
list = "left"  # Configure layout for list pages
single = true # Configure layout for single pages
# Enable widgets in given order
widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets.social]
github = "AtsushiSaito"